### ISSUE TITLE
error after importing

### ISSUE THREAD

**Issue by Pilly170** [Abdulraheem30042/Cl0neMast3r#1]
Imported current directory - all went OK
Display your tools - Error Below

`Please wait to update tools list
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/clonemaster/Cl0neMast3r.py", line 256, in update
    Tool.list = [Tool(tool.strip(), True) for tool in resource]
  File "/opt/clonemaster/Cl0neMast3r.py", line 33, in __init__
    self.lastInstall = self.lastInstall() if self.isInstalled else "Couldn't retrieve the date"
  File "/opt/clonemaster/Cl0neMast3r.py", line 46, in lastInstall
    return self.strpTime(open(self.name + "/install", "r").read())
  File "/opt/clonemaster/Cl0neMast3r.py", line 106, in strpTime
    return datetime.strptime(date, "%Y-%m-%d %H:%M:%S")
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '#!/usr/bin/env python\n#HEAD#########################################################\n#\n# Katana Framework | install                         \n# Last Modified: 14/03/2017\n#\n#########################################################HEAD#\n\nfrom core import Information, colors, Update\nimport os, time, subprocess\nfrom sys import stdout\n\ndef Command_exe(msg,cmd):\n\ti = "\\033[1mSTATUS"+colors.W+":[Processing]"\n\tstdout.write(" " + msg + " %s" % i)\n\tstdout.flush()\n\tif subprocess.call(cmd+\' >/dev/null 2>&1\', shell=True)==0:\n\t\ti = "[\\033[1m"+colors.G+"OK"+colors.W+"]"\n\telse:\n\t\ti = "["+colors.R+"\\033[1mERROR"+colors.W+"]["+colors.O+"\\033[1mWARNING"+colors.W+"]"\n\t\t\n\tstdout.write("\\r " + msg +" STATUS:%s" % i)\n\nprint ""\nprint "                    "+colors.B+",:"+colors.W+"       "+colors.B+":,"+colors.W+"                   \t\t\t\t "#                    ,:       :,                   \nprint "                   "+colors.B+",/./"+colors.W+" _8_  "+colors.B+"\\.\\                  \t\t\t\t "#                   /./  _8_  \\.\\                  \nprint "                   "+colors.B+",\\ \\\\"+colors.W+"/"+colors.P+"("+colors.R+"O"+colors.P+")"+colors.W+"\\\\"+colors.B+"/ /                  \t\t\t\t "#                   \\ \\/( O )\\/ /                  \nprint "                    "+colors.B+",\\ \\:::/ /                   \t\t\t\t "#                    \\ \\:::::/ /                   \nprint "                     /"+colors.O+"__"+colors.G+"---"+colors.O+"__"+colors.B+"\\                   \t\t\t\t "#                     /__---__\\                    \nprint "                    ("+colors.O+"/__\\ /__\\\\"+colors.B+")"+colors.W+"                   \t\t\t\t "#                    (/__\\ /__\\)                   \nprint "                    "+colors.B+"/"+colors.W+"\\  .V.  /"+colors.B+"\\\\"+colors.W+"                   \t\t\t\t "#                    /\\  .V.  /\\                   \nprint "                   "+colors.B+"/"+colors.W+"  \\,---,/  "+colors.B+"\\\\"+colors.W+"                  \t\t\t\t "#                   /  \\,---,/  \\                  \nprint "                   "+colors.B+"\\\\"+colors.W+"___TTTTT___"+colors.B+"/"+colors.W+"         CODE: KATANA  "#                   \\___TTTTT___/                  \nprint "                ::::\\ "+colors.R+"|"+colors.W+"_____"+colors.R+"|"+colors.W+" /::::      DATE: "+Information.date+""#                ::::\\ "+colors.R+"|"+colors.W+"_____"+colors.R+"|"+colors.W+" /::::               \nprint "                (+  _"+colors.R+"|"+colors.W+" __"+colors.R+"|"+colors.W+"__ "+colors.R+"|"+colors.W+"_  +)      CORE: "+Information.version+", BUILD: "+Information.build #                (+  _"+colors.R+"|"+colors.W+" __"+colors.R+"|"+colors.W+"__ "+colors.R+"|"+colors.W+"_  +)               \nprint "        "+Information.Type+"    "+colors.R+"|"+colors.W+"  I_"+colors.R+"|"+colors.W+"KATANA."+colors.R+"|"+colors.W+"_I  "+colors.R+"|"+colors.W+"                               "#                "+colors.R+"|"+colors.W+"  I_"+colors.R+"|"+colors.W+".ANATAK"+colors.R+"|"+colors.W+"_I  "+colors.R+"|"+colors.W+"               \nprint "                "+colors.R+"|"+colors.W+"  I_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"  "+colors.R+"|"+colors.W+"               \t\t\t\t "#                "+colors.R+"|"+colors.W+"  I_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"  "+colors.R+"|"+colors.W+"               \nprint "    __________?_____________________________________  \t\t\t\t "#    __________?_________________________________  \nprint "   {_"+colors.C+"B|"+colors.W+" "+colors.C+"Y|"+colors.W+" "+colors.R+"R|"+colors.W+" "+colors.W+"T|"+colors.W+" |"+colors.GR+"#################################"+colors.W+"/  \t\t\t\t "#   {_"+colors.R+"|"+colors.W+" "+colors.R+"|"+colors.W+" "+colors.R+"|"+colors.W+" "+colors.R+"|"+colors.W+" I#################################/  \nprint "     ^ ^ ^ ^   ,ww   "+colors.O+"FRAMEWORK"+colors.W+"   ww,                   \t\t\t\t "#     ^ ^ ^ ^ EHT KROWEMARF, dliuB      \nprint "                   I_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_I                  \t\t\t\t "#                   I_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_I                  \nprint "                   \\_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_/                  \t\t\t\t "#                   \\_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_"+colors.R+"|"+colors.W+"_/                  \nprint ""\nprint ""\n\nif os.getuid() != 0:\n\tprint " ["+colors.R+"-"+colors.W+"] ERROR:"+colors.B+" Katana Install"+colors.B+" must be run as "+colors.R+"root"+colors.W+"."\n\tprint " ["+colors.R+"-"+colors.W+"] login as root ("+colors.R+"sudo"+colors.W+") or try "+colors.W+"sudo python install"+colors.W+"\\n"\n\texit(1)\ntime.sleep(1)\n\nShortcuts ="ln -f -r -s /usr/share/KatanaFramework/core/shorts/ktf.console /usr/bin/ktf.console ; ln -f -r -s /usr/share/KatanaFramework/core/shorts/ktf.linker  /usr/bin/ktf.linker  ; ln -f -r -s /usr/share/KatanaFramework/core/shorts/ktf.update  /usr/bin/ktf.update  ; ln -f -r -s /usr/share/KatanaFramework/core/shorts/ktf.ktf     /usr/bin/ktf.ktf     ; ln -f -r -s /usr/share/KatanaFramework/core/shorts/ktf.tool    /usr/bin/ktf.tool    ; ln -f -r -s /usr/share/KatanaFramework/core/shorts/ktf.gui     /usr/bin/ktf.gui     ; ln -f -r -s /usr/share/KatanaFramework/core/shorts/ktf.run     /usr/bin/ktf.run "\nFiles     ="cp -r * /usr/share/KatanaFramework/doc/man/ /usr/local/share/man/man1/   ; cd /usr/share/KatanaFramework/files/                                     ; tar xvf /usr/share/KatanaFramework/files/exiftool.tar >/dev/null 2>&1    ; tar xvf /usr/share/KatanaFramework/files/getdatareport.tar >/dev/null 2>&1; rm -R /usr/share/KatanaFramework/files/*.tar              ; rm /usr/share/KatanaFramework/install                     ; rm /usr/share/KatanaFramework/dependencies                ; rm /usr/share/KatanaFramework/README.md "\nPreinstall="rm -f /usr/bin/ktf.console; rm -f /usr/bin/ktf.linker; rm -f /usr/bin/ktf.update; rm -f /usr/bin/ktf.ktf; rm -f /usr/bin/ktf.tool; rm -f /usr/bin/ktf.run; rm -f /usr/bin/ktf.gui; "\n\nprint " INSTALLING"\nprint Command_exe("["+time.strftime(\'%H:%M:%S\')+"] Pre-installing.                  ",Preinstall)\nprint Command_exe("["+time.strftime(\'%H:%M:%S\')+"] Checking dependencies.           ",\'sudo bash dependencies\')\nprint " ["+time.strftime(\'%H:%M:%S\')+"] Checking Updates."\nUpdate.update("installer",True)\nprint ""\nprint Command_exe("["+time.strftime(\'%H:%M:%S\')+"] Creating Folder.                 ",\'mkdir -p /usr/share/KatanaFramework\')\nprint Command_exe("["+time.strftime(\'%H:%M:%S\')+"] Copying files.                   ",\'cp -r * /usr/share/KatanaFramework\')\nprint Command_exe("["+time.strftime(\'%H:%M:%S\')+"] Creating Shortcuts.              ",Shortcuts)\nprint Command_exe("["+time.strftime(\'%H:%M:%S\')+"] Extracting Files.                ",Files)\nprint Command_exe("["+time.strftime(\'%H:%M:%S\')+"] Giving privileges.               ",\'chmod -R -c 750 /usr/share/KatanaFramework/\')\n\nprint "\\n If all is [OK] Katana was installed, use ktf.console or ktf.gui (DEMO)"\nprint " go to https://github.com/PowerScript/KatanaFramework/wiki for more info\\n"\n' does not match format '%Y-%m-%d %H:%M:%S'
`

**Comment by Abdulrah33m** [comment]
Thank you for reporting this issue
Issue has been fixed please check commit [4398b9e](https://github.com/Abdulraheem30042/Cl0neMast3r/commit/bd00705f277964c55a414f4a5a1c33f897e55872)
