### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by maddog9696** [Abdulraheem30042/Cl0neMast3r#10]
I have ran the tool many times with no issues. However, I went to run it today and keep getting an error. Have no idea why it is not working or what broke it. I am on Kali Linux 2018.1 and have double checked to make sure all dependency's are installed. The error occurs right after opening the tool and letting it sit for 5 seconds. And none of the options work, they all just freeze.

[A] Add a tool using URL
[F] Find a tool on GitHub
[R] Reinstall your tools
[U] Update your tools
[S] Display your tools
[D] Delete tools list
[X] Export tools to HTML
[M] Import your tools
[E] Exit 
How can I help you: Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Cl0neMast3r.py", line 256, in update
    Tool.list = [Tool(tool.strip(), True) for tool in resource]
  File "Cl0neMast3r.py", line 34, in __init__
    self.lastUpdate = self.lastUpdate()
  File "Cl0neMast3r.py", line 42, in lastUpdate
    return self.strpTime(str(s.find("relative-time")['datetime'].replace("T", " ")[:-1]))
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Abdulrah33m** [comment]
Hello Michael,
Sorry for this bug. Can you please send me the list of your tools, so I can recognize the error reason
You can share it here or send privately to my Twitter account @abdulrah33mk

**Comment by maddog9696** [comment]
So I recently copied my list of URL's from the ToolsList.txt file. Then I deleted the Cl0neMast3r folder and re-downloaded and installed it. It is now fully working. I just copied and pasted the list of tools back into the ToolsList.txt and all errors have been solved. So im not sure what caused the issue. Program runs fine now and completes with no errors?

**Comment by maddog9696** [comment]
I think it was perhaps an incorrectly formatted URL in the tools list perhaps? I dont know how that happend because i used the option in the tool to add the URL. And like I said, I just moved the ToolsList.txt to my desktop, deleted Cl0neMaster, reinstalled and copied the ToolsList.txt file back into the Cl0neMaster directory. Glad everything works now tho! Awsome program, thanks so much for your hard work!

**Comment by maddog9696** [comment]
FIXED: Caused by deleting a tool manually from ToolsList.txt.
Whoops...Guess you cant remove a tool this way!
