### ISSUE TITLE
[Windows] - Testing for fun

### ISSUE THREAD

**Issue by vwhissell** [Abdulraheem30042/Cl0neMast3r#2]
Got this with Windows and Anaconda2

![image](https://user-images.githubusercontent.com/18213053/37036919-1c36a588-211f-11e8-87a0-c98fb1ade24a.png)

Maybe you can think of a fix for all those characters, hehe ;-)

**Comment by vwhissell** [comment]
Oh I thought that Windows Support was right on the corner, but was wrong corry man.

Things like this:
```
for tool in listToUpdate:
			print green + "\n[" + tool.name + "]" + end
			tool.remove("/tmp/")
			tool.clone("/tmp/")
			tool.copy()
tool.remove("/tmp/")
```
Win Support is a bit far. But hey, very nice job! This tool is great!
You coding is awesome also, I like it.
Easy to read, but also made with adv. python. Love it.

**Comment by Abdulrah33m** [comment]
Thank you,
Cl0neMaster will supports windows soon, it would need cup of coffee and couple of hours ;)
Happy that you like it, wait for the next upate I’m sure you will love it also.
