### ISSUE TITLE
Updating Tools

### ISSUE THREAD

**Issue by Pilly170** [Abdulraheem30042/Cl0neMast3r#4]
Tried updating (option 2)

`How can I help you: U
[Updating your tool]
Please wait to update tools list
[1] Update all tools
[2] Update old tools
**Choose 1 or 2: 2**
Traceback (most recent call last):
  File "/opt/clonemaster/Cl0neMast3r.py", line 321, in <module>
    Tool.update()
  File "/opt/clonemaster/Cl0neMast3r.py", line 202, in update
    listToUpdate = [tool for tool in cls.list if not tool.isUpToDate]
AttributeError: Tool instance has no attribute 'isUpToDate'
`

**Comment by Abdulrah33m** [comment]
Thanks for reporting this issue.
Issue has been fixed in commit [8de90c6](https://github.com/Abdulraheem30042/Cl0neMast3r/commit/8de90c677bf5b1dc0670deede6e7f5ca7307e6f0)
