### ISSUE TITLE
Lastest build

### ISSUE THREAD

**Issue by Pilly170** [Abdulraheem30042/Cl0neMast3r#5]
`python /opt/clonemaster/Cl0neMast3r.py 

Traceback (most recent call last):
  File "/opt/clonemaster/Cl0neMast3r.py", line 1, in <module>
    oovin# coding: utf-8
NameError: name 'oovin' is not defined`

**Comment by Abdulrah33m** [comment]
Sorry for this it was my fault :D
You can check it now

**Comment by Pilly170** [comment]
looks ok. cheers
