### ISSUE TITLE
Add option update from default online list

### ISSUE THREAD

**Issue by Zarcolio** [Abdulraheem30042/Cl0neMast3r#6]
Hi Abdul,

First of all, what a great tool you've built!

I have a small request.
Can you add an option to configure a URL from which it can import tools.
I'd like to save my list of tools in Github and configure the raw URL inside Cl0neMast3r.
This way I only have to update my online list :)

**Comment by Abdulrah33m** [comment]
Thanks a lot happy to hear that 😃 
Please send me your suggestion on my Twitter account [abdulrah33mk](https://twitter.com/abdulrah33mk)
